const express = require('express');
const { query, validationResult } = require('express-validator');
const { Transaction, Item, User, Request, AuditLog } = require('../database/models');
const { authenticateToken, requireAdmin } = require('../middleware/auth');
const logger = require('../utils/logger');

const router = express.Router();

// GET /api/report/transactions - Get transaction report (admin only)
router.get('/transactions', [
  query('start_date')
    .optional()
    .isISO8601()
    .withMessage('Start date must be a valid ISO date'),
  query('end_date')
    .optional()
    .isISO8601()
    .withMessage('End date must be a valid ISO date'),
  query('type')
    .optional()
    .isIn(['request', 'pickup', 'restock', 'adjustment'])
    .withMessage('Type must be one of: request, pickup, restock, adjustment'),
  query('item_id')
    .optional()
    .isInt()
    .withMessage('Item ID must be an integer'),
  query('user_id')
    .optional()
    .isInt()
    .withMessage('User ID must be an integer'),
  query('format')
    .optional()
    .isIn(['json', 'csv'])
    .withMessage('Format must be json or csv')
], authenticateToken, requireAdmin, async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        error: 'Validation failed',
        details: errors.array()
      });
    }

    const { 
      start_date, 
      end_date, 
      type, 
      item_id, 
      user_id, 
      format = 'json',
      page = 1,
      limit = 100
    } = req.query;

    let whereClause = {};

    // Date range filter
    if (start_date || end_date) {
      whereClause.created_at = {};
      if (start_date) {
        whereClause.created_at[require('sequelize').Op.gte] = new Date(start_date);
      }
      if (end_date) {
        whereClause.created_at[require('sequelize').Op.lte] = new Date(end_date);
      }
    }

    // Type filter
    if (type) {
      whereClause.type = type;
    }

    // Item filter
    if (item_id) {
      whereClause.item_id = item_id;
    }

    // User filter
    if (user_id) {
      whereClause.user_id = user_id;
    }

    const offset = (page - 1) * limit;

    const { count, rows: transactions } = await Transaction.findAndCountAll({
      where: whereClause,
      include: [
        { 
          model: Item, 
          as: 'item', 
          attributes: ['id', 'nama_barang', 'satuan'] 
        },
        { 
          model: User, 
          as: 'user', 
          attributes: ['id', 'username', 'role'],
          required: false
        },
        { 
          model: Request, 
          as: 'request', 
          attributes: ['id', 'status', 'is_urgent', 'is_public_request'],
          required: false
        }
      ],
      order: [['created_at', 'DESC']],
      limit: format === 'csv' ? null : parseInt(limit),
      offset: format === 'csv' ? null : parseInt(offset)
    });

    // Log audit
    await AuditLog.logAction({
      user_id: req.user.id,
      action: 'system_action',
      ip_address: req.ip,
      user_agent: req.get('User-Agent'),
      details: {
        action: 'generate_transaction_report',
        filters: { start_date, end_date, type, item_id, user_id },
        format,
        total_records: count
      }
    });

    logger.info(`Transaction report generated by ${req.user.username}: ${count} records`);

    if (format === 'csv') {
      // Generate CSV format
      const csvHeader = 'ID,Date,Type,Item,User,Quantity,Previous Stock,New Stock,Notes\n';
      const csvRows = transactions.map(t => {
        return [
          t.id,
          t.created_at.toISOString(),
          t.type,
          `"${t.item?.nama_barang || 'N/A'}"`,
          `"${t.user?.username || 'System'}"`,
          t.quantity,
          t.previous_stock,
          t.new_stock,
          `"${(t.notes || '').replace(/"/g, '""')}"`
        ].join(',');
      }).join('\n');

      const csvContent = csvHeader + csvRows;

      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="transaction_report_${new Date().toISOString().split('T')[0]}.csv"`);
      
      return res.send(csvContent);
    }

    // JSON format
    res.json({
      transactions,
      summary: {
        total_transactions: count,
        date_range: {
          start: start_date || 'All time',
          end: end_date || 'Present'
        },
        filters: {
          type: type || 'All types',
          item_id: item_id || 'All items',
          user_id: user_id || 'All users'
        }
      },
      pagination: format === 'json' ? {
        current_page: parseInt(page),
        total_pages: Math.ceil(count / limit),
        total_items: count,
        per_page: parseInt(limit)
      } : null,
      generated_at: new Date().toISOString(),
      generated_by: req.user.username
    });

  } catch (error) {
    next(error);
  }
});

// GET /api/report/summary - Get summary statistics (admin only)
router.get('/summary', [
  query('period')
    .optional()
    .isIn(['today', 'week', 'month', 'year'])
    .withMessage('Period must be one of: today, week, month, year')
], authenticateToken, requireAdmin, async (req, res, next) => {
  try {
    const { period = 'month' } = req.query;

    // Calculate date range based on period
    const now = new Date();
    let startDate;

    switch (period) {
      case 'today':
        startDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
        break;
      case 'week':
        startDate = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
        break;
      case 'month':
        startDate = new Date(now.getFullYear(), now.getMonth(), 1);
        break;
      case 'year':
        startDate = new Date(now.getFullYear(), 0, 1);
        break;
    }

    const whereClause = {
      created_at: {
        [require('sequelize').Op.gte]: startDate
      }
    };

    // Get transaction counts by type
    const transactionCounts = await Transaction.findAll({
      where: whereClause,
      attributes: [
        'type',
        [require('sequelize').fn('COUNT', require('sequelize').col('id')), 'count']
      ],
      group: ['type'],
      raw: true
    });

    // Get request counts by status
    const requestCounts = await Request.findAll({
      where: {
        created_at: {
          [require('sequelize').Op.gte]: startDate
        }
      },
      attributes: [
        'status',
        [require('sequelize').fn('COUNT', require('sequelize').col('id')), 'count']
      ],
      group: ['status'],
      raw: true
    });

    // Get low stock items
    const lowStockItems = await Item.findAll({
      attributes: ['id', 'nama_barang', 'stok_terkini', 'minimum_stock'],
      where: require('sequelize').literal('stok_terkini <= minimum_stock'),
      order: [['stok_terkini', 'ASC']]
    });

    // Get total items and stock value
    const totalItems = await Item.count();
    const totalStock = await Item.sum('stok_terkini');

    // Get active users (users who made transactions in the period)
    const activeUsers = await Transaction.findAll({
      where: whereClause,
      attributes: [
        [require('sequelize').fn('COUNT', require('sequelize').fn('DISTINCT', require('sequelize').col('user_id'))), 'count']
      ],
      raw: true
    });

    res.json({
      period,
      date_range: {
        start: startDate.toISOString(),
        end: now.toISOString()
      },
      transactions: {
        by_type: transactionCounts.reduce((acc, curr) => {
          acc[curr.type] = parseInt(curr.count);
          return acc;
        }, {}),
        total: transactionCounts.reduce((sum, curr) => sum + parseInt(curr.count), 0)
      },
      requests: {
        by_status: requestCounts.reduce((acc, curr) => {
          acc[curr.status] = parseInt(curr.count);
          return acc;
        }, {}),
        total: requestCounts.reduce((sum, curr) => sum + parseInt(curr.count), 0)
      },
      inventory: {
        total_items: totalItems,
        total_stock: totalStock || 0,
        low_stock_items: lowStockItems.length,
        low_stock_list: lowStockItems.slice(0, 10) // Top 10 low stock items
      },
      users: {
        active_in_period: parseInt(activeUsers[0]?.count || 0)
      },
      generated_at: new Date().toISOString(),
      generated_by: req.user.username
    });

  } catch (error) {
    next(error);
  }
});

// GET /api/report/audit-logs - Get audit logs (admin only)
router.get('/audit-logs', [
  query('start_date')
    .optional()
    .isISO8601()
    .withMessage('Start date must be a valid ISO date'),
  query('end_date')
    .optional()
    .isISO8601()
    .withMessage('End date must be a valid ISO date'),
  query('action')
    .optional()
    .isString()
    .withMessage('Action must be a string'),
  query('user_id')
    .optional()
    .isInt()
    .withMessage('User ID must be an integer')
], authenticateToken, requireAdmin, async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        error: 'Validation failed',
        details: errors.array()
      });
    }

    const { 
      start_date, 
      end_date, 
      action, 
      user_id,
      page = 1,
      limit = 50
    } = req.query;

    let whereClause = {};

    // Date range filter
    if (start_date || end_date) {
      whereClause.timestamp = {};
      if (start_date) {
        whereClause.timestamp[require('sequelize').Op.gte] = new Date(start_date);
      }
      if (end_date) {
        whereClause.timestamp[require('sequelize').Op.lte] = new Date(end_date);
      }
    }

    // Action filter
    if (action) {
      whereClause.action = action;
    }

    // User filter
    if (user_id) {
      whereClause.user_id = user_id;
    }

    const offset = (page - 1) * limit;

    const { count, rows: auditLogs } = await AuditLog.findAndCountAll({
      where: whereClause,
      include: [
        { 
          model: User, 
          as: 'user', 
          attributes: ['id', 'username', 'role'],
          required: false
        }
      ],
      order: [['timestamp', 'DESC']],
      limit: parseInt(limit),
      offset: parseInt(offset)
    });

    res.json({
      audit_logs: auditLogs,
      pagination: {
        current_page: parseInt(page),
        total_pages: Math.ceil(count / limit),
        total_items: count,
        per_page: parseInt(limit)
      },
      filters: {
        start_date: start_date || 'All time',
        end_date: end_date || 'Present',
        action: action || 'All actions',
        user_id: user_id || 'All users'
      },
      generated_at: new Date().toISOString(),
      generated_by: req.user.username
    });

  } catch (error) {
    next(error);
  }
});

module.exports = router; 